options:
  logging: CLOUD_LOGGING_ONLY
steps:
# Reservations Service
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-east4-docker.pkg.dev/reservations-472613/reservations/production',
        '-f',
        './apps/reservations/Dockerfile',
        '.'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-east4-docker.pkg.dev/reservations-472613/reservations/production',
      ]
# Notification Service
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-east4-docker.pkg.dev/reservations-472613/notifications/production',
        '-f',
        './apps/notifications/Dockerfile',
        '.'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-east4-docker.pkg.dev/reservations-472613/notifications/production',
      ]
# Auth Service
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-east4-docker.pkg.dev/reservations-472613/auth/production',
        '-f',
        './apps/auth/Dockerfile',
        '.'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-east4-docker.pkg.dev/reservations-472613/auth/production',
      ]
# Payments Service
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-east4-docker.pkg.dev/reservations-472613/payments/production',
        '-f',
        './apps/payments/Dockerfile',
        '.'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-east4-docker.pkg.dev/reservations-472613/payments/production',
      ]