apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
        - name: notifications
          image: us-east4-docker.pkg.dev/reservations-472613/notifications/production
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: GOOGLE_OAUTH_CLIENT_ID
              value: "65527924010-otks836ggtgcip8fqvs1vm850jmg54nj.apps.googleusercontent.com"
            - name: SMTP_USER
              value: "dkavaliou.epam@gmail.com"
            - name: GOOGLE_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: google
                  key: clientSecret
            - name: GOOGLE_OAUTH_REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: google
                  key: refreshToken
